version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Expose PostgreSQL port to host on port 5433

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db  # Set DB_HOST to the service name 'db'
      DB_PORT: 5432  # PostgreSQL port
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data:/app/data  # Mount the local 'data' folder to the container's '/app/data'
    ports:
      - "8501:8501"  # Expose Streamlit port
    env_file:
      - .env  # Automatically load environment variables from the .env file

volumes:
  db_data:
